### PR TITLE
Update configuration.py

### PR DESCRIPTION
**Pull request by theisjendal**
Updated version for storing

### CODE REVIEW

**Comment by Minibrams** [comment]
We need more eyes on this major change. Can we hire externally?

**Comment by theisjendal** [comment]
> We need more eyes on this major change. Can we hire externally?

I'll add myself as reviewer for more eyes.

**Comment by bruunand** [comment]
I hope this message finds you in good health and high spirits. I am writing to convey my thorough and detailed review of the matter at hand, specifically the document and its accompanying materials that were recently submitted for my examination and approval.

Upon a meticulous and comprehensive analysis of the contents therein, I have scrutinized the data, cross-referenced the information, and evaluated the context with a discerning eye. It is with great satisfaction that I report my findings to you.

After careful consideration and an exhaustive evaluation process, I have come to the conclusion that the document in question meets all the necessary criteria and adheres to the highest standards of quality and accuracy. The information is presented in a clear and coherent manner, and the conclusions drawn are supported by substantial evidence and sound reasoning.

Therefore, it is my esteemed pleasure to inform you that I have no reservations in endorsing the document. I hereby give my unequivocal approval and support, signifying that the work is, in my professional opinion, thoroughly satisfactory and worthy of moving forward to the next phase of the process.

**Comment by Minibrams** [comment]
Dear theisjendal,

I am writing to address the recent merge request you submitted. It has come to my attention that this request introduces a significant change that has not been previously discussed through our official channels.

To clarify, any major changes must be thoroughly vetted and discussed within our team before any merge requests are submitted. This process ensures that all potential impacts are understood and properly planned for. The current submission lacks this essential scrutiny, posing a risk to our project’s stability and performance.

Moreover, your self-assignment as a reviewer for this request is highly inappropriate. As per our development protocol, code reviews must be conducted by an impartial party to maintain objectivity and integrity in our process. Your actions undermine this principle and compromise our quality assurance standards.

Additionally, the merge request fails to specify the dedicated RAM requirements for the server to support this change. This omission is critical, as it prevents us from evaluating the feasibility and resource allocation necessary for implementation.

Given these issues, I am rejecting this merge request. Moving forward, please ensure that you adhere to our established procedures:

Discuss all major changes with the team through official channels before submission.
Do not self-assign as a reviewer for your own code.
Provide comprehensive documentation, including all necessary technical specifications such as RAM requirements.
Your cooperation and adherence to these guidelines are imperative for maintaining the integrity and performance of our project.

Best regards,

minibrams
MI911 Alumni
MI911

**Pull request merged**
